### ISSUE TITLE
Trending page won't load when using a European IP address

### ISSUE THREAD

**Issue by ChunkyProgrammer** [FreeTubeApp/yt-trending-scraper#11]
I believe it's a "Cookie consent verification" required issue
https://github.com/FreeTubeApp/FreeTube/pull/2125#issuecomment-1075125771

I believe the solution would be something like this

https://github.com/FreeTubeApp/yt-comment-scraper/blob/ff0c885de2053ef92d80e26d4861a9b7cc634986/src/HttpRequester.js#L20

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This should be fixed now.

**Comment by ChunkyProgrammer** [comment]
It's fixed when using FreeTube but not fixed for other people that use the module

**Comment by GilgusMaximus** [comment]
Mhh, for me running all the tests, gives me failure of the following ones.
![image](https://user-images.githubusercontent.com/34301369/177214939-b7610186-89f1-4956-a6e9-0eb517faee18.png)

I also manually checked the returned data of the normal requests, but it seems that it is working form my German ip. Do all of these work at least in FreeTube?

**Comment by ChunkyProgrammer** [comment]
> Mhh, for me running all the tests, gives me failure of the following ones. ![image](https://user-images.githubusercontent.com/34301369/177214939-b7610186-89f1-4956-a6e9-0eb517faee18.png)
> 
> I also manually checked the returned data of the normal requests, but it seems that it is working form my German ip. Do all of these work at least in FreeTube?

I believe this is working in FreeTube now as the consent cookie is set in the app (see https://github.com/FreeTubeApp/FreeTube/pull/2316).

**Comment by ChunkyProgrammer** [comment]
seems to be an issue with the shorts regex and not an issue with European IP addresses

**Comment by ChunkyProgrammer** [comment]
see #17

**Comment by GilgusMaximus** [comment]
Okay so I investigated a bit further on #17 , I run into the problem because the module gets me everything in German, so the regex for English time units doesn't work. I identified the following cookie to determine the language at the end for me, but setting it like below doesn't change it for me.

![image](https://user-images.githubusercontent.com/34301369/177398440-9393d896-7c94-4693-9141-2172c6fbab49.png)


Some ideas on that
